version: "3"

services:
   server:
      build: .
      container_name: server
      ports:
        -  "90:80"
      volumes:
        - ./database/projects:/app/dgantt/projects
        - ./database/data:/app/dgantt/data
