<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo "<title>Time Sheet ".$project_name."</title>"; ?>
<?php 
echo '<link rel="stylesheet" type="text/css" media="screen" href="'.TIMESHEET_FOLDER.'/css/css-table.css" />';
?>
<style type="text/css" media="screen">
@import url(css/css-report.css);
a:link, a:visited, a:active {
	color: #000;
	text-decoration: underline;
}
</style>
<?php 
echo '<script type="text/javascript" src="'.TIMESHEET_FOLDER.'/js/jquery-1.2.6.min.js"></script>';
echo '<script type="text/javascript" src="'.TIMESHEET_FOLDER.'/js/style-table.js"></script>';
?>

</head>

<body>

<table id="timelog" summary="Hello">

    
    <thead>    
    	<tr>

		
		
            <th scope="col" rowspan="2"><h3>Tasks for Week ending <?php echo $date;?></h3></th>
            <th scope="col" colspan=" <?php echo count($rows[0])  ?> ">Time Spent - Week 
				<select onChange="ComboChange(this)">
				<?php
					foreach($weeklist as $wek=>$value)
					{
						
						if(intval($wek) == intval($week))
							echo '<option value="'.$value.'" selected>'.$wek.'</option>';
						else	 
							echo '<option value="'.$value.'">'.$wek.'</option>';
					}
				/*	<option value="41">4</option>
					<option value="3">3</option>
					<option value="2">2</option>
					<option value="1">1</option>*/
				?>
				</select>
			</th>
        </tr>
        
        <tr>
		<?php  
			$authors = $rows['header'];	
			foreach($authors as $author)
				echo '<th scope="col">'.$author.'</th>';
		?>
        
        </tr>        
    </thead>
    
    <tfoot>
    	<tr>
        	<th scope="row">Total Days</th>
			<?php     
			$total = 0;
			$row = $rows['footer'];
			foreach($row as $timespent)
			{
				
				$total = round($timespent,1);
				if($timespent < .1)
					echo '<td>'.round($timespent,2).'</td>';
				else
					echo '<td>'.round($timespent,1).'</td>';
			}
			?>
        
        </tr>
    </tfoot>
    
    <tbody>
		<?php
			for($i=0;$i<(count($rows)-2);$i++)
			{
				echo '<tr>';
				echo '<th scope="row">'.$rows[$i][0]->link.'</th>';
				for($j=1;$j<count($rows[$i]);$j++)
				{	if($rows[$i][$j] < .1)
						echo  '<td>'.round($rows[$i][$j],2).'</td>';
					else
						echo  '<td>'.round($rows[$i][$j],1).'</td>';
					
				}
				echo '</tr>';
			}
		?>
    	
    </tbody>

</table>




<script type='text/javascript'>
    function ComboChange(a)
    {
        //value = document.getElementById(a.value);
						//$project_file = "'".JSGANTT_FOLDER.$organization."/".$project_name."/".$subplan."/jsgantt.xml?v=1'";
		
		this.document.location.href = '<?php echo $link;  ?>'+'&date='+a.value;

		
    }
</script>

<?php
$link .= '&layout=3&date='.$date;
echo '<a  style="color:#999;" href="'.$link.'" title="" target="_blank">Task View</a>';

$link .= '&layout=1&date='.$date;
echo '&nbsp&nbsp<a  style="color:#999;" href="'.$link.'" title="" target="_blank">User View</a>';
?>
<!-- Designed by DreamTemplate. Please leave link unmodified. -->
<br><a  style="color:#999;" href="none" title="" target="_blank">Report Generated by DGantt Tools</a>

</body>
</html>