<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php echo "<title>Time Sheet ".$project_name."</title>"; ?>
<?php 
echo '<link rel="stylesheet" type="text/css" media="screen" href="'.TIMESHEET_FOLDER.'/css/css-table.css" />';
?>
<style type="text/css" media="screen">
@import url(css/css-report.css);
a:link, a:visited, a:active {
	color: #000;
	text-decoration: underline;
}
</style>
<?php 
echo '<script type="text/javascript" src="'.TIMESHEET_FOLDER.'/js/jquery-1.2.6.min.js"></script>';
echo '<script type="text/javascript" src="'.TIMESHEET_FOLDER.'/js/style-table.js"></script>';
?>

</head>

<body>

<table id="timelog" summary="Hello">
<col width="80%">
<col width="10%">
<col width="10%">
<?php

$tasks = array();

$authors = $rows['header'];	



$worklog = $rows['footer'];
$total = $worklog[count($worklog)-1];

for($i=0;$i<(count($rows)-2);$i++)
{
	$task = new Obj();
	$task->users = array();
	$task->name =  $rows[$i][0]->link;
	$task->jiraid = $rows[$i][0]->jiraid;
	for($j=1; $j< count($rows[$i])-1 ;$j++)
	{
		if($rows[$i][$j] > 0)
		{
			//echo $authors[$j].EOL;
			$task->users[] = $authors[$j-1];
		}
		//echo $rows[$i][$j].EOL;
	}
	$task->worklog =  $rows[$i][count($rows[$i])-1];;
	$tasks[] = $task;
}


//$row = $rows['footer'];
//foreach($row as $timespent)
//{
//	echo round($timespent,1).EOL;
//}
?>
	<thead>    
		<tr>
            
			<th scope="col"><h3>Time Sheet - Week 
				<select onChange="ComboChange(this)">
				<?php
					foreach($weeklist as $wek=>$value)
					{
						
						if(intval($wek) == intval($week))
							echo '<option value="'.$value.'" selected>'.$wek.'</option>';
						else	 
							echo '<option value="'.$value.'">'.$wek.'</option>';
					}
				?>
				</select>
				</h3>
				<h3>Ending <?php echo $date;?></h3>
			</th>
			
			<th scope="col"><h3>Users</h3>
			 </th>
           <th scope="col" rowspan="2"><h3>Days</h3></th>
        </tr>
        
          
    </thead>
	
	<tbody>
		<?php
			foreach($tasks as $task)
			{
				echo '<tr>';
					echo '<th scope="row">';
						echo $task->name;
					echo '</th>';
					echo '<td>';
						
						foreach($task->users as $usr)
						{
							$lnk = 'timesheet?layout=1&board='.$board.'&user='.$usr.'&date='.$date;
							echo '&nbsp&nbsp'.'<a href="'.$lnk.'">'.$usr.'</a>';
						}
					echo '</td>';
					echo '<td>';
						if($task->worklog < .1)
							echo round($task->worklog,2);
						else
							echo round($task->worklog,1);
					echo '</td>';
				echo '</tr>';
			}
		?>
    	
    </tbody>
	<tfoot>
    	<tr>
			<?php     
			echo '<tr>';
					echo '<td>';
						echo 'Total';
					echo '</td>';
					echo '<td>';
					echo '</td>';
					echo '<td>';
						echo round($total,1).' days';
					echo '</td>';
				echo '</tr>';
			?>
        
        </tr>
    </tfoot>
</table>



<script type='text/javascript'>
    function ComboChange(a)
    {
        //value = document.getElementById(a.value);
						//$project_file = "'".JSGANTT_FOLDER.$organization."/".$project_name."/".$subplan."/jsgantt.xml?v=1'";
		
		this.document.location.href = '<?php echo $link;  ?>'+'&date='+a.value;

		
    }
</script>

<?php
$link .= '&layout=3&date='.$date;
echo '<a  style="color:#999;" href="'.$link.'" title="" target="_blank">Task View</a>';

$link .= '&layout=1&date='.$date;
echo '&nbsp&nbsp<a  style="color:#999;" href="'.$link.'" title="" target="_blank">User View</a>';
?>

<!-- Designed by DreamTemplate. Please leave link unmodified. -->
<br><a  style="color:#999;" href="none" title="" target="_blank">Report Generated by DGantt Tools</a>

</body>
</html>